# Generated by Django 6.0.6 on 2026-07-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jirauser')),
            ],
        ),
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_key', models.CharField(max_length=100, unique=True)),
                ('ticket_type', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('estimated_time', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('assigned_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jira.assigneduser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraproject')),
            ],
        ),
        migrations.CreateModel(
            name='JiraTicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerScore', models.FloatField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraticket')),
            ],
        ),
    ]
