# Generated by Django 6.0.6 on 2026-07-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraticket',
            name='description_quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraticket',
            name='startingDate_priority_logical_relation_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraticket',
            name='storyPoint_estimatedTime_logical_relation_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraticket',
            name='story_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraticket',
            name='summary_quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
