# Generated by Django 6.0.6 on 2026-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_jiraticket_description_quality_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraticket',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
