# Generated by Django 6.0.6 on 2026-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_alter_assigneduser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigneduser',
            name='fullName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
