# Generated by Django 6.0.6 on 2026-07-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_alter_jiraticket_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraticket',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jira.assigneduser'),
        ),
    ]
