# Generated by Django 6.0.6 on 2026-07-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_alter_assigneduser_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigneduser',
            old_name='fullName',
            new_name='_fullName',
        ),
    ]
