# Generated by Django 6.0.6 on 2026-07-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_alter_jiraticket_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_coefficient', models.IntegerField()),
                ('description_coefficient', models.IntegerField()),
                ('priority_check_coefficient', models.IntegerField()),
                ('estimated_time_check_coeffichient', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraproject')),
            ],
        ),
    ]
