# Generated by Django 6.0.6 on 2026-07-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_rename_fullname_assigneduser__fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigneduser',
            old_name='_fullName',
            new_name='fullName',
        ),
    ]
