# Generated by Django 6.0.6 on 2026-07-08 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_rename__fullname_assigneduser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigneduser',
            name='fullName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
