# Generated by Django 6.0.6 on 2026-07-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_coefficient'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryDescriptionFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keyWords', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.coefficient')),
                ('jira_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jirauser')),
                ('description_mandatory_fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jira.mandatorydescriptionfields')),
            ],
        ),
    ]
