# Generated by Django 6.0.6 on 2026-07-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0006_alter_assigneduser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraticket',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
