# Generated by Django 6.0.6 on 2026-07-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0006_mandatorydescriptionfields_configurationdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationdata',
            name='jira_user',
        ),
    ]
