# Generated by Django 6.0.6 on 2026-07-08 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0007_alter_jiraticket_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraticket',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
