# Generated by Django 6.0.6 on 2026-07-13 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0007_remove_configurationdata_jira_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationdata',
            name='description_mandatory_fields',
        ),
        migrations.AddField(
            model_name='configurationdata',
            name='configuration_json',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MandatoryDescriptionFields',
        ),
    ]
