# Generated by Django 6.0.6 on 2026-07-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0008_jiraticket_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField()),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraticket')),
            ],
        ),
        migrations.CreateModel(
            name='PriorityTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_relation_score', models.IntegerField()),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraticket')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField()),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraticket')),
            ],
        ),
    ]
